apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gps-inventory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/celso2003/ProyectoGPSInventorMicroservice.git
    path: proyectogps-deploy-k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
