apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gps-inventory
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/inventory: ghcr.io/celso2003/proyectogpsinventormicroservice/inventory-microservice
    argocd-image-updater.argoproj.io/inventory.update-strategy: latest
spec:
  project: default
  source:
    repoURL: "https://github.com/celso2003/ProyectoGPSInventorMicroservice.git"
    targetRevision: main
    path: proyectogps-deploy-k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
