apiVersion: apps/v1
kind: Deployment
metadata:
  name: gps-inventory
  labels:
    app: gps-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gps-inventory
  template:
    metadata:
      labels:
        app: gps-inventory
    spec:
      containers:
        - name: gps-inventory
          image: ghcr.io/celsosan2003/inventario-app:latest
          ports:
            - containerPort: 3001
