apiVersion: v1
kind: Service
metadata:
  name: gps-users-microservice
  labels:
    app: gps-users-microservice
spec:
  type: ClusterIP
  selector:
    app: gps-users-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
