apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gps-inventory-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gps-inventory
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
