apiVersion: v1
kind: Service
metadata:
  name: gps-inventory-service
  labels:
    app: gps-inventory
spec:
  type: LoadBalancer
  selector:
    app: gps-inventory
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
