apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gps-inventory-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gps-inventory
