prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'argo-workflows'
        static_configs:
          - targets: ['argo-workflow-controller.argo.svc.cluster.local:9090']

      - job_name: 'argo-server'
        static_configs:
          - targets: ['argo-server.argo.svc.cluster.local:8080']

      - job_name: 'argocd-server'
        static_configs:
          - targets: ['argocd-server.argocd.svc.cluster.local:8083']
